### ISSUE TITLE
Generating incorrect code

### ISSUE THREAD

**Issue by as641651** [HPAC/linnea#25]
I use this  [script](https://github.com/as641651/linnea/blob/exp/experiment-suite/01_generate_test_expressions.py) to generate Julia codes. I get incorrect code (non-deterministic) for some Application examples. 

Some errors:

Application 05
![image](https://user-images.githubusercontent.com/19472192/75561073-ab843400-5a46-11ea-9ea8-79315755f15b.png)

Application 16 (operand sizes from "operand_generator.jl" and the requirements in generated code does not match
![image](https://user-images.githubusercontent.com/19472192/75561290-0ae24400-5a47-11ea-9f2b-d86c3cb873b8.png)

Also it would be better if the variable id numbers in the generated code are reset every time graph.write_output is called

**Comment by henrik227** [comment]
I will look into it. Which Julia version are you using?

> Also it would be better if the variable id numbers in the generated code are reset every time graph.write_output is called

I don't think this should happen in `graph.write_output()`. If anything, this should be part of `linnea.config.clear_all()`.

**Comment by as641651** [comment]
I use Julia version Version 1.1.0-DEV.468. But the problem is with code generation itself

I do call `linnea.config.clear_all()` before calling `graph.write_output()`, but still the variable ids don't reset

**Comment by henrik227** [comment]
> I use Julia version Version 1.1.0-DEV.468. But the problem is with code generation itself

Well, as I found out, the problem with `findn` is that it was deprecated in some previous Julia version.

> I do call `linnea.config.clear_all()` before calling `graph.write_output()`, but still the variable ids don't reset

Yes, because this feature is not implemented yet. I just said that I would implement it in `linnea.config.clear_all()` instead of `graph.write_output()`.

> I get incorrect code (non-deterministic) for some Application examples.

Regarding the non-determinism: What exactly is non-deterministic? Do you run the generated code twice (_without_ rerunning Linnea in between), or is the code that gets generated different between different runs of Linnea? The latter is expected, due to operating system noise and how the search algorithm works: How long the search runs is determined by the `time_limit` argument of `graph.derivation()`. Depending on stuff like operating system noise, Linnea might be able to do more or less work in this amount of time, and thus may find different algorithms between different runs. To avoid this, you could either run the generation on a system with less noise, or you increase the generation time. Linnea still finds many new solutions around 10 seconds into the generation (the time limit you specified). If you increase this number to a few minutes, it gets less likely that you get different results, because not as many new solutions are found around this time.

Finally, could you please send the me Julia code for application 16 that produces the dimension mismatch error?

**Comment by henrik227** [comment]
> Also it would be better if the variable id numbers in the generated code are reset every time graph.write_output is called

Do you mean the numbers of the memory locations (the variables starting with `ml`)? What I was thinking of already happens, so we are probably talking about different things.

**Comment by as641651** [comment]
> What exactly is non-deterministic? Do you run the generated code twice (without rerunning Linnea in between), or is the code that gets generated different between different runs of Linnea?

It's the latter.

These were the applications that had some error when I generated the codes last time. This list is not always the same (That’s what I meant by non-deterministic)

['results/Application_13', 'results/Application_23', 'results/Application_09', 'results/Application_22', 'results/Application_08', 'results/Application_16', 'results/Application_14', 'results/Application_12', 'results/Application_24', 'results/Application_15', 'results/Application_11']

> Finally, could you please send the me Julia code for application 16 that produces the dimension mismatch error?

I emailed the generated code for application 16

> Do you mean the numbers of the memory locations (the variables starting with ml)? 

Yes. For eg, If I generate code for application 1 and 2 in a loop and application 1 has algorithms with variable names unto ml122. The algorithm 0 in application 2 starts with variable name ml123. I thought it would be nice if it was reset to ml0.

**Comment by henrik227** [comment]
Can you please check if the problem with the incorrect code is fixed now?

Regarding the variable names: While this is not what you asked for, now the variable names in _all_ algorithms start from `ml0`.

**Comment by as641651** [comment]
Now getting this error

```
ERROR: LoadError: UndefVarError: Property not defined
Stacktrace:
 [1] operand_generator() at /home/user/linnea-Feb20/experiment-suite/test_expressions_sample/Application_24/Julia/operand_generator.jl:4
 [2] main() at /home/user/linnea-Feb20/experiment-suite/test_expressions_sample/Application_24/Julia/runner_t1.jl:14
```

> Regarding the variable names: While this is not what you asked for, now the variable names in all algorithms start from ml0.

Thank you!

**Comment by henrik227** [comment]
> Now getting this error
> 
> ```
> ERROR: LoadError: UndefVarError: Property not defined
> Stacktrace:
>  [1] operand_generator() at /home/user/linnea-Feb20/experiment-suite/test_expressions_sample/Application_24/Julia/operand_generator.jl:4
>  [2] main() at /home/user/linnea-Feb20/experiment-suite/test_expressions_sample/Application_24/Julia/runner_t1.jl:14
> ```

I fixed this a few minutes ago; please pull the latest version.

**Comment by as641651** [comment]
Yes, it's working now. Thank you!
