### ISSUE TITLE
Why Python rather than Julia?

### ISSUE THREAD

**Issue by crstnbr** [HPAC/linnea#28]
Hi there,

First of all, great tool!

Out of curiosity, given that Linnea produces Julia code eventually, why isn't it also implemented in Julia (rather than Python)? Any particular considerations?

Best,
Carsten

**Comment by hbarthels** [comment]
Thank you very much!

There are multiple reasons: When we started working on Linnea, we didn't plan to generate Julia code, but C. However, we didn't want to implement such a research project in a low-level language like C, and we had some code from another project that was written in Python that was useful for Linnea (code for pattern matching, which is now done with [MatchPy](https://github.com/HPAC/matchpy)). That's why we went with Python.

We are now generating C code instead of Julia because we realized that with Julia, we could get something working more quickly. While we mostly use BLAS and LAPACK kernels, we also need code snippets for operations not supported by those libraries, and code for converting the storage formats of matrices. Writing that code with decent performance was much easier in Julia. I think it would still be nice to generate C code at some point.

So I would say all of this can be summarized as "historical reasons". 😉

I think that reimplementing Linnea in Julia, making use of Julia's metaprogramming features, could be a good way to make it easily accessible to a larger audience. Unfortunately, I don't know if and when that might happen.

**Comment by crstnbr** [comment]
Fair enough, thanks for the insights! Generating C would of course be great the have (although I'll call myself a Julia enthusiast 😄). Also, you could probably make the output code a bit more "Julian", for example by being more type generic and allowing, say, `Float32` as well (types supported by LAPACK). Anyways, nice project!
