### ISSUE TITLE
Wrong FLOPs calculation for SCAL?

### ISSUE THREAD

**Issue by as641651** [HPAC/linnea#29]
Shouldn't this be M*N?

https://github.com/HPAC/linnea/blob/c8fb5d1f64666bf63d35859484a5041ff75dbb90/linnea/kernels/julia/kernels.py#L653

**Comment by pauldj** [comment]
looks like you are right - it also looks like some sort of a typo
lambda M, N: M * N,

**Comment by hbarthels** [comment]
No, this is correct. Look at this line:

https://github.com/HPAC/linnea/blob/c8fb5d1f64666bf63d35859484a5041ff75dbb90/linnea/kernels/julia/kernels.py#L655

There, `MN` is defined as the number of _entries_ of `X`. It would have also been possible to use two separate `SizeArgument`s for `M` and `N`, but this way it's possible to directly insert the number of entries in the function call (instead of a product `rows * columns`).
